services:
  server:
    build:
      context: "./"
      dockerfile: "./server.Dockerfile"
    image: "server:v1"
    container_name: "server"
    ports:
      - "7070:7070"
    networks:
      - internet

  client:
    build: 
      context: "./"
      dockerfile: "./client.Dockerfile"
    depends_on: [server]
    image: "client:v1"
    container_name: "client"
    networks:
      - internet
networks:
  internet:
    external: true
